# Atomic blocks

## ARMA model

### Introduction

The ARMA process is defined by

$$\Phi\left(B\right)y_t=\Theta\left(B\right)\epsilon_t $$

where:

$$\Phi\left(B\right)=1+\varphi_1 B + \cdots + \varphi_p B^p $$

$$\Theta\left(B\right)=1+\theta_1 B + \cdots + \theta_q B^q $$

are the auto-regressive and the moving average polynomials.

The MA representation of the model is $y_t=\sum_{i=0}^\infty {\psi_i \epsilon_{t-i}}$. Let $\gamma_i$ be the autocovariances of the model. We also define: $r=\max\left(p, q+1\right), \quad s=r-1$.

The state-space model can be written in different ways. JD+ provides two of them

### Representation I

#### State vector

$$ \alpha_t= \begin{pmatrix} y_t \\ y_{t+1|t} \\ \vdots \\ y_{t+s|t} \end{pmatrix}$$

where $y_{t+i|t}$ is the orthogonal projection of $y_{t+i}$ on the subspace generated by ${y\left(s\right):s \leq t}$.Thus, it is the forecast function with respect to the semi-infinite sample. We also have that $y_{t+i|t} = \sum_{j=i}^\infty {\psi_j \epsilon_{t+i-j}}$

#### Dynamics

$$ T_t = \begin{pmatrix}0 &1 & 0 & \cdots & 0  \\0& 0 & 1 & \cdots & 0\\ \vdots & \vdots & \vdots & \ddots & \vdots\\ 0 & 0 & 0 & \cdots & 1\\
-\varphi_r & \cdots  & \cdots & \cdots &-\varphi_1 \end{pmatrix}$$

with $\varphi_{j}=0$ for $j>p$

$$ S_t = \begin{pmatrix}1 \\ \psi_1 \\ \vdots\\ \psi_s \end{pmatrix} $$

$$ V_t = S S' $$

#### Measurement

$$ Z_t = \begin{pmatrix} 1 & 0 & \cdots & 0\end{pmatrix}$$

$$ h_t = 0 $$

#### Initialization

$$ \alpha_{-1} = \begin{pmatrix}0 \\ 0 \\ \vdots\\ 0 \end{pmatrix} $$

$$ P_{*} = \Omega $$

$\Omega$ is the unconditional covariance of the state array; it can be easily derived using the MA representation. We have:

$$ \Omega\left(i,0\right) = \gamma_i $$

$$ \Omega\left(i,j\right) = \Omega\left(i-1,j-1\right)-\psi_i \psi_j $$

### Representation II

We provide below an alternative state space representation as follows

#### State vector:

$$ \alpha_t= \begin{pmatrix} y_t \\ 
-\varphi_2 y_{t-1}-\dots-\varphi_r y_{t-r+1}+\theta_1 \epsilon_t+ \dots + \theta_{r-1} \epsilon_{t-r+2}\\ -\varphi_3 y_{t-1}-\dots-\varphi_r y_{t-r+2}+\theta_2 \epsilon_t+ \dots + \theta_{r-1} \epsilon_{t-r+3}\\ \vdots \\ 
-\varphi_r y_{t-1}+\theta_{r-1} \epsilon_{t}
\end{pmatrix}$$

#### Dynamics

$$ T_t = \begin{pmatrix}-\varphi_1 &1 & 0 & \cdots & 0  \\
-\varphi_2& 0 & 1 & \cdots & 0\\ 
\vdots & \vdots & \vdots & \ddots & \vdots\\ 
\vdots & 0 & 0 & \cdots & 1\\
-\varphi_r & 0  & \cdots & \cdots &0 \end{pmatrix}$$

$$ S_t = \begin{pmatrix}1 \\ \theta_1 \\ \vdots\\ \theta_r \end{pmatrix} $$

$$ V_t = S S' $$

#### Measurement

$$ Z_t = \begin{pmatrix} 1 & 0 & \cdots & 0\end{pmatrix}$$

$$ h_t = 0 $$

#### Initialization

$$ \alpha_{-1} = \begin{pmatrix}0 \\ 0 \\ \vdots\\ 0 \end{pmatrix} $$

$$ P_{*} = \Omega $$

$\Omega$ is the unconditional covariance of the state array; it can be easily derived using the MA representation. We have:

$$ \Omega\left(i,0\right) = \gamma_i $$

$$ \Omega\left(i,j\right) = \Omega\left(i-1,j-1\right)-\psi_i \psi_j $$

## Time dependent ARMA model

### Introduction

The time dependent ARMA process (TDARMA) is defined by

$$ \Phi_t\left(B\right)y_t=\Theta_t\left(B\right)\epsilon_t $$

where:

$$\Phi_t\left(B\right)=1+\varphi_{t,1} B + \cdots + \varphi_{t,p} B^p $$

$$\Theta_t\left(B\right)=1+\theta_{t,1} B + \cdots + \theta_{t,q} B^q $$

are the time dependent auto-regressive and the moving average polynomials.

### State vector:

$$ \alpha_t= \begin{pmatrix} y_t \\ 
-\varphi_{t+1,2} y_{t-1}-\dots-\varphi_{t+1,r} y_{t-r+1}+\theta_{t+1,1} \epsilon_t+ \dots + \theta_{t+1, r-1} \epsilon_{t-r+2}\\ -\varphi_{t+2,3} y_{t-1}-\dots-\varphi_{t+2,r} y_{t-r+2}+\theta_{t+2,2 }\epsilon_t+ \dots + \theta_{t+2,r-1} \epsilon_{t-r+3}\\ \vdots \\ 
-\varphi_{t+r-1,r} y_{t-1}+\theta_{t+r-1,r-1} \epsilon_{t}
\end{pmatrix}$$

### Dynamics

$$ \alpha_{t+1} = T_t \alpha_t + \begin{pmatrix} 1 \\ \theta_{t+2,1} \\ \theta_{t+3,2} \\ \vdots \\  \theta_{t+r, r-1} \\ \end{pmatrix} \epsilon_{t+1} $$

$$ T_t = \begin{pmatrix}-\varphi_{t+1,1} &1 & 0 & \cdots & 0  \\
-\varphi_{t+2,2} & 0 & 1 & \cdots & 0\\ 
\vdots & \vdots & \vdots & \ddots & \vdots\\ 
\vdots & 0 & 0 & \cdots & 1\\
-\varphi_{t+r,r} & 0  & \cdots & \cdots &0 \end{pmatrix}$$

$$ S_t = \begin{pmatrix}\sigma_{t+1}\\ \sigma_{t+1} \theta_{t+2,1} \\ \vdots\\ \sigma_{t+1} \theta_{t+r,r-1} \end{pmatrix} $$

$$ V_t = S S' $$

### Measurement

$$ Z_t = \begin{pmatrix} 1 & 0 & \cdots & 0\end{pmatrix}$$

$$ h_t = 0 $$

### Initialization

$$ \alpha_0= \begin{pmatrix} y_0 \\ 
-\varphi_{1,2} y_{-1}-\dots-\varphi_{1,r} y_{-r+1}+\theta_{1,1} \epsilon_0+ \dots + \theta_{1, r-1} \epsilon_{-r+2}\\ -\varphi_{2,3} y_{-1}-\dots-\varphi_{2,r} y_{-r+2}+\theta_{2,2 }\epsilon_0+ \dots + \theta_{2,r-1} \epsilon_{-r+3}\\ \vdots \\ 
-\varphi_{r-1,r} y_{-1}+\theta_{r-1,r-1} \epsilon_{0}
\end{pmatrix}$$

The covariance of $\alpha_0$ can be easily computed, taking into account that $y_0, \dots,y_{r-1}$ and $\epsilon_0, \dots, \epsilon_{r-1}$ are generated by the same processes and that their variances/covariances are:

$$ cov(y_i, y_j)=\gamma(i-j)$$

$$ cov(y_i, \epsilon_j) = \psi_{j-i}\sigma^2, j\le i$$

$$ cov(\epsilon_i, \epsilon_j)=\sigma^2, i=j $$

## ARIMA model

### Introduction

We consider that the auto-regressive polynomial contains some unit roots. It can be factorized in a stationary polynomial (defined by the roots outside the unit circle) and in a non-stationary polynomial (defined by the roots on the unit circle), which is notated:

$$ \Delta\left(B\right) = 1 + \delta_1 B + \cdots + \delta_d B^d $$

The state space form of an ARIMA model is similar to the state space form of an ARMA model, except for its initialization.

### Initialization

The initial conditions can be written as follows:

$$ \alpha_{-1} = \begin{pmatrix}1 \\ 0 \\ \vdots\\ 0 \end{pmatrix} $$

$$ P_{*} = \Sigma \Omega \Sigma' $$

$$ B = \Lambda $$

$$ P_{\infty}= \Lambda \Lambda' $$

$\Omega$ is the unconditional covariance of the state array of the stationary model.

$$ \Sigma = \begin{pmatrix} 1 & 0 & \cdots & 0 \\ \lambda_1 & 1 & \cdots & 0 \\ \lambda_2 & \lambda_1 & \cdots & \vdots\\ \vdots & \vdots & \vdots & \vdots \\ \lambda_{r-1} & \lambda_{r-2} & \cdots & \lambda_{1} \end{pmatrix} $$

where $\lambda_{i}$ are generated by $\frac{1}{\Delta\left(B\right)}$

$\Lambda$ is a r x d matrix; its first d rows form an identity matrix; other cells are defined by the recursive relationship:

$$\Lambda \left(i,j\right) = -\sum_{k=1}^d {\delta_k \Lambda \left(i-k,j\right)}$$

## Noise

## Local level

## Local linear trend

## Seasonal component

### Introduction

The seasonal component provided in JD+ is based on Proietti\[2000\]

We consider that it is composed of latent variables corresponding to each period, which follow a multivariate random walk. We also impose that the sum of the latent variables is 0 at each point time.

### State vector

For a periodicity of $s$, we define the state space form of the seasonal component as follows (West-Harrison form):

We consider first the state vector $\tilde \gamma_t$ such that $\tilde \gamma_{it}$ is the (unobserved) seasonal component of season $i$ observed at time $t$.

Using that definition would imply a time varying measurement error. To avoid it, we use the state vector $\gamma_t$ which is a rotation of $\tilde \gamma_t$ such that the first component corresponds to the current period. More precisely, $\gamma_{it} =\tilde\gamma_{\left( \left(t-i\right) \mod s \right), t}$.

Moreover, the constraint that the sum of the latent variables is 0 allows us to consider only $s-1$ periods (the missing one being the opposite of the sum of all the other periods).

### Dynamics

$$ T_t = \begin{pmatrix} 0 & 1 & \cdots & 0 \\ \vdots & \ddots & \ddots & \vdots \\ 0 &  \cdots & 0 & 1  \\ -1 & -1 & \cdots & -1\end{pmatrix}$$

The covariance matrix of the innovations can take various form. Using the terminology of Proietti, we consider:

| Model | V | S |
|------------------------|------------------------|------------------------|
| Dummy | $\begin{pmatrix} 0 &  \cdots & 0 \\ \vdots & & \vdots\\ 0 &\cdots &\sigma_{seas}^2\end{pmatrix}$ | $\begin{pmatrix}0 \\ \vdots \\ \sigma_{seas}\end{pmatrix}$ |
| Crude | $\sigma_{seas}^2\begin{pmatrix} 1 &  \cdots & 1 \\ \vdots & & \vdots\\ 1 &\cdots & 1\end{pmatrix}$ | $\sigma_{seas}\begin{pmatrix}1 \\ \vdots \\ 1\end{pmatrix}$ |
| HarrisonStevens | $\sigma\_{seas}\^2$ |  |
| Trigonometric |  |  |

### Measurement

$$ Z_t = \begin{pmatrix} 1 & 0 & \cdots & 0\end{pmatrix}$$

### Bibliography

Proietti T. (2000), "Comparing seasonal components for structural time series models", International Journal of Forecasting, 16, 2, 247-260.

## Cyclical component

### Introduction

A Cycle component is a special case of an AR2 component, which contains two complex conjugate roots.

More precisely, it is defined by a period $\lambda$ and a dumping factor $\rho$. If $\gamma = \frac{2\pi}{\lambda}$, we have that

$$   \begin{pmatrix} y_{t+1} \\ y^*_{t+1}\end {pmatrix} = \begin{pmatrix} \rho \cos{\gamma} &&   \rho \sin{\gamma}\\  -\rho \sin{\gamma}  && \rho \cos{\gamma}\end {pmatrix}\begin{pmatrix} y_t \\ y_t^*\end {pmatrix}+\begin{pmatrix} \epsilon_t \\ \epsilon_t^*\end {pmatrix} $$

Using those notations, the state-space model can be written as follows :

### State vector:

$$ \alpha_t= \begin{pmatrix} y_t \\ y_t^* \end{pmatrix}$$

### Dynamics

$$ T_t = \begin{pmatrix} \rho \cos{\gamma} &&   \rho \sin{\gamma}\\  -\rho \sin{\gamma}  && \rho \cos{\gamma}\end {pmatrix}$$

$$ S_t = \sigma_c \begin{pmatrix} 1 && 0\\  0  && 1\end {pmatrix} $$

$$ V_t = \sigma_c^2\begin{pmatrix} 1 && 0\\  0  && 1\end {pmatrix} $$

### Measurement

$$ Z_t = \begin{pmatrix} 1 & 0 \end{pmatrix}$$

$$ h_t = 0 $$

### Initialization

$$ \a_{-1} = \begin{pmatrix}0 \\ 0 \end{pmatrix} $$

$$ P_{*} =  \sigma_c^2\begin{pmatrix} \frac{1}{1-\rho^2} && 0\\  0  && \frac{1}{1-\rho^2}\end {pmatrix} $$
