# Overview

## Description of the general model

The `general linear gaussian` state-space model can be written in many different ways. The form considered in JD+ ($\ge 3.0$) is presented below:

$$ y_t = Z_t \alpha_t + \epsilon_t,\quad \epsilon_t \sim N\left(0, \sigma^2 H_t\right),\quad t> 0$$

$$ \alpha_{t+1} = T_t \alpha_t + \mu_t, \quad \mu_t \sim N \left(0, \sigma^2 V_t \right),\quad t \ge 0 $$

$y_t$ is the observation at period t, $\alpha_t$ is the state vector. $\epsilon_t, \mu_t$ are assumed to be serially independent at all leads and lags and independent from each other.\
In the case of multi-variate models, $y_t$ is a vector of observations. However, in most cases, we will use the univariate approach by considering the observations one by one (univariate handling of multi-variate models).

The innovations of the state equation will be modelled as

$$ \mu_t = S_t \xi_t, \quad \xi_t \sim N\left( 0, \sigma^2 I\right) $$

In other words, $V_t=S_t S_t'$

The initial ($\equiv t=0$) conditions of the filter are defined as follows:

$$ \alpha_{0} = a_{0} + B\delta + \mu_{0}, \quad \delta \sim N\left(0, \kappa I \right),\: \mu_{0} \sim N\left(0, P_*\right)$$

where $\kappa$ is arbitrary large. $P_*$ is the variance of the stationary part of the initial state vector and $B$ models the diffuse part. We write $BB'=P_\infty$.

The definition used in JD+ is quasi-identical to that of Durbin and Koopman\[1\].

In summary, the model is completely defined by the following quantities (possible default values are indicated in brackets):

$$ \mathbf{Z_t}, \mathbf{H_t} [=0] $$

$$ \mathbf{T_t}, \mathbf{V_t} [=S_t S_t'], \mathbf{S_t} [=Cholesky(V)] $$

$$ \mathbf{a_{0}}[=0], \mathbf{P_*} [=0], \mathbf{B} [=0], \mathbf{P_\infty} [=BB'] $$
The following notations are used in all the pages related to the ssf framework:

$$ a_{t+k|t}=E\left(\alpha_{t+k} | y_0 \cdots y_{t}\right)$$

$$ P_{t+k|t}=cov\left(\alpha_{t+k} | y_0 \cdots y_{t}\right)$$

$$ a_{t+1}=a_{t+1|t}, \: P_{t+1}=P_{t+1|t} $$

Finally, it should be noted that all the indexes of arrays or matrices start at 0 (Java and C++ convention).

## Algorithms

State space models are convenient representations of time series to derive multiple properties. Algorithms has been developed around them for likelihood evaluation (and so, for parameters estimation), for filtering/forecasting, for smoothing/missing values estimation, for simulation...

Multiple variations of those algorithms have been developed, to favor either speed, memory use, robustness or accuracy.

The JD+ framework provides several family of those algorithms, mainly based on approaches developed by Durbin-Koopman (DK), De Jong (AKF or Augmented Kalman Filter), Kailath (Array filters) or Chandrasekhar filters (CKMS or Chandrasekhar-Kailath-Morf-Sidhu). They will be described in the chapter 3.

## Design



